### PR TITLE
fix: remove memory leak

### PR DESCRIPTION
**Pull request by jeswr**
This PR:
 - Solves the memory leak issue in `n3reasoner` by removing listeners from the process event (and also closes the issue in #95 ).
 - Throws an error rather than logging a console warning if eye or SWIPL error as part of the `n3reason` function call
 - Adds a bunch of testing for memory leaks in Node and browser (hopefully some of which will also be added upstream in https://github.com/emscripten-core/emscripten/issues/18723 at some point)
 - Increases our general test coverage; including full-blown e2e tests in Firefox and Chrome browsers.

### CODE REVIEW

**Comment by jeswr** [comment]
https://github.com/eyereasoner/eye-js/pull/110/commits/1f9a1f7be8f9cf6435ed4c13efc58ac3664743d6 closes #114

**Comment by jeswr** [comment]
@josd Please do not merge this yet


@josd @smessie  This is going to be a mver update so if we want to make any other breaking changes I suggest we do them as part of this PR.

Personally; I think the default behavior of `n3reasoner` should be changed to output either derivations or deductive closure by default. This is because with the current default running  `n3reasoner(dataQuads)` returns an empty array when the data quads are the standard socrates data input of

```
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix : <http://example.org/socrates#>.

:Socrates a :Human.
:Human rdfs:subClassOf :Mortal.

{?A rdfs:subClassOf ?B. ?S a ?A} => {?S a ?B}.
```

**Review by josd — APPROVED** [review]
Is a quite substantial change and as far as I could look, there are no burning remarsks from my side.

**Comment by jeswr** [comment]
Superceded by #123

**Pull request closed without merging**
